#!/usr/bin/env python3

import argparse
import json
import os
import re
import subprocess
import sys

## Database Functions

def read_db(db):
	with open(db) as fp:
		return json.load(fp)

def write_db(db, d):
	with open(db, 'w') as fp:
		fp.write(json.dumps(d, indent=4))

def run(arg, cmd):
	if arg.verbose: print(cmd, file=sys.stderr, end=' ...')
	ret = subprocess.run(cmd, shell=True).returncode
	if ret != 0:
		raise Exception(f'{cmd} failed with status {ret}')
	if arg.verbose: print(f' done', file=sys.stderr)

## Subcommand Functions

def create(arg, env):
	db = f'{env}/seqxtant.json'
	if os.path.isfile(db):
		raise Exception(f'seqxtant databse already exists at {db}')
	write_db(db, {'state': 'ready', 'genomes': []})

def status(arg, env):
	db = f'{env}/seqxtant.json'
	if not os.path.isfile(db):
		raise Exception(f'{db} is not a seqxtant database location')
	print(f'Data location: {db}')
	d = read_db(db)
	print(f'Database status: {d["state"]}')
	print(f'Genomes: {len(d["genomes"])}')
	for genome in d['genomes']:
		print(f'\t{genome}')

def add_genome(arg, env):
	db = f'{env}/seqxtant.json'
	d = read_db(db)
	if d['state'] == 'busy' and not arg.force:
		raise Exception(f'cannot add genome, {db} is currently busy')
	if arg.genome in d['genomes'] and not arg.force:
		raise Exception(f'cannot add genome, {arg.genome} already present')

	# copy files to build directory under new names
	d['state'] = 'busy'
	write_db(db, d)
	dna = f'{arg.env}/{arg.genome}.fa'
	msk = f'{arg.env}/{arg.genome}.masked.fa'
	gff  = f'{arg.env}/{arg.genome}.gff3'
	
	# genome
	if arg.fasta.endswith('.gz'):
		run(arg, f'cp -f {arg.fasta} {dna}.gz')
		run(arg, f'gunzip -f {dna}.gz')
	else:
		run(arg, f'cp -f {arg.fasta} {dna}')
	
	# masked genome
	if arg.masked.endswith('.gz'):
		run(arg, f'cp -f {arg.masked} {msk}.gz')
		run(arg, f'gunzip -f {msk}.gz')
	else:
		run(arg, f'cp -f {arg.masked} {msk}')
	
	# gff3
	if arg.gff3.endswith('.gz'):
		run(arg, f'cp -f {arg.gff3} {gff}.gz')
		run(arg, f'gunzip -f {gff}.gz')
	else:
		run(arg, f'cp -f {arg.gff3} {gff}')
	
	# make blast databases
	write_db(db, d)
	run(arg, f'xdformat -n -I {dna}')
	run(arg, f'xdformat -n -I {msk}')
	
	# done
	if arg.genome not in d['genomes']: d['genomes'].append(arg.genome)
	d['state'] = 'ready'
	write_db(db, d)

def validate_genome(arg, env):
	db = f'{env}/seqxtant.json'
	d = read_db(db)
	
	if arg.genome not in d['genomes']:
		raise Exception(f'{arg.genome} not found in database')
	
	ff = f'--fasta {arg.env}/{arg.genome}.fa'
	g3 = f'--gff {arg.env}/{arg.genome}.gff3'
	ht = f'--html {arg.html} --tables {arg.tables}'
	
	run(arg, f'calfo --title {arg.genome} {ff} {g3} {ht}')

def cbe(s):
	m = re.search('(\S+):([\d,]+)[\-\.]+([\d,]+)', s)
	if not m: raise Exception('location string malformed')
	c = m.group(1)
	b = int(m.group(2).replace(',', ''))
	e = int(m.group(3).replace(',', ''))
	return c, b, e

def store_fasta(arg, env, masked=False):
	c, b, e = cbe(arg.location)
	if masked:
		infile = f'{env}/{arg.genome}.masked.fa'
		outfile = f'{arg.odir}/query.masked.fa'
	else:
		infile = f'{env}/{arg.genome}.fa'
		outfile = f'{arg.odir}/query.fa'
	
	cmd = f'xdget -n -a {b} -b {e} {infile} {c}'
	proc = subprocess.run(cmd, shell=True, capture_output=True)
	if proc.returncode != 0: raise Exception(f'xdget failed: {proc.stderr}')
	lines = proc.stdout.decode().split('\n')
	lines[0] = f'>{arg.genome}-{arg.location}'
	length = - len(lines[0])
	with open(outfile, 'w') as fp:
		for line in lines:
			length += len(line)
			fp.write(line)
			fp.write('\n')
	return length

def run_blast(arg, env, target):
	qf = f'{arg.odir}/query.masked.fa'
	db = f'{env}/{target}.fa'
	of = f'{arg.odir}/{target}.blastn'
	params = (
		'M=1 N=-1 Q=2 R=2',              # alignment
		'B=999 V=999 mformat=2',         # reporting
		'topcomboN=999',                 # grouping
		'warnings',                      # quiet
		'golmax=10',
		f'E={arg.evalue}',               # filtering
		f'W={arg.wordsize}',             # capturing
		f'hspsepSmax={arg.maxintron}',   # genome-dependent
		f'cpus={arg.cpus}',
	)
	opts = ' '.join(params)
	cmd = f'ab-blastn {db} {qf} -o {of} {opts}'
	run(arg, cmd)
	
	# read and organize HSPs
	hsps = {}
	with open(of) as fp:
		for line in fp:
			if line.startswith('#'): continue
			f = line.split()
			qid = f[0]
			sid = f[1]
			ev = float(f[2])
			sc = int(f[5])
			st = f[16][0]
			qb = int(f[17])
			qe = int(f[18])
			sb = int(f[20])
			se = int(f[21])
			gr = f[22]
			if st == '-': (qb, qe) = (qe, qb)
			
			if sid not in hsps: hsps[sid] = {}
			if st not in hsps[sid]: hsps[sid][st] = {}
			if gr not in hsps[sid][st]: hsps[sid][st][gr] = []
			hsps[sid][st][gr].append( (qb, qe, sb, se, sc, ev) )
	
	for sid in hsps:
		for strand in hsps[sid]:
			for grp in hsps[sid][strand]:
				hsps[sid][strand][grp].sort( key=lambda x: x[0])
				yield qid, sid, strand, hsps[sid][strand][grp]

def getseq(filename, c, b, e, strand):
	infile = f'{env}/{filename}.fa'
	if strand == '-': (b, e) = (e, b)
	cmd = f'xdget -n -a {b} -b {e} {infile} {c}'
	proc = subprocess.run(cmd, shell=True, capture_output=True)
	if proc.returncode != 0: raise Exception(f'xdget failed: {proc.stderr}')
	lines = proc.stdout.decode().split('\n')
	return ''.join(lines[1:])

def cluster(arg, env):
	db = f'{env}/seqxtant.json'
	d = read_db(db)
	if d['state'] == 'busy': raise Exception(f'database is busy')
	
	if not os.path.isdir(arg.odir):
		os.mkdir(arg.odir)
		os.mkdir(f'{arg.odir}/seqs')
	
	rlen = store_fasta(arg, env)
	store_fasta(arg, env, masked=True)
	
	if arg.limit: targets = arg.limit
	else:         targets = d['genomes']

	uid = 0
	summary = []
	for target in targets:
		if arg.genome == target and not arg.paralogs: continue
		for qid, sid, strand, hsps in run_blast(arg, env, target):
			qb = hsps[0][0]
			qe = hsps[-1][1]
			ev = hsps[0][5]
			if strand == '+':	
				sb = hsps[0][2]
				se = hsps[-1][3]
			else:
				sb = hsps[-1][2]
				se = hsps[0][3]
			seq = getseq(target, sid, sb, se, strand)
			loc = f'{target}:{sid}:{sb}-{se}{strand}'
			ls = len(seq)
			with open(f'{arg.odir}/seqs/{uid}.fa', 'w') as fp:
				fp.write(f'>{uid} {loc} {ev} {ls}\n')
				for i in range(0, len(seq), 80):
					fp.write(seq[i:i+80])
					fp.write('\n')
			summary.append( (uid, target, sid, sb, se, strand, ev, ls) )
			uid += 1
	
	# write summary file
	with open(f'{arg.odir}/summary.txt', 'w') as fp:
		for uid, tid, sid, sb, se, st, ev, ln in summary:
			fp.write(f'{uid}\t{tid}\t{sid}\t{sb}\t{se}\t{st}\t{ev}\t{ln}\n')

## CLI top-level ##
parser = argparse.ArgumentParser(description='genomic homology multi-mapper')
parser.add_argument('--env',
	help='set data location instead of $SEQXTANT')
parser.add_argument('--verbose', action='store_true',
	help='see behind the scenes messages')
subparsers = parser.add_subparsers(required=True,
	help='sub-commands')

### status sub-command
parse_status = subparsers.add_parser('status',
	help='get information about the database')
parse_status.set_defaults(func=status)

### create sub-command
parse_create = subparsers.add_parser('create',
	help='create a new database')
parse_create.set_defaults(func=create)

### add sub-command
parse_add = subparsers.add_parser('add',
	help='add new genome to database')
parse_add.add_argument('--genome', required=True,
	help='genome name, e.g. C.elegans')
parse_add.add_argument('--fasta', required=True,
	help='genome in fasta')
parse_add.add_argument('--masked', required=True,
	help='hard-masked genome in fasta')
parse_add.add_argument('--gff3', required=True,
	help='annotation in gff3')
parse_add.add_argument('--force', action='store_true',
	help='force overwrite of previous data')
parse_add.set_defaults(func=add_genome)

### validate sub-command
parse_validate = subparsers.add_parser('validate',
	help='validate genome to check for errors')
parse_validate.add_argument('--genome', required=True,
	help='genome name, e.g. C.elegans')
parse_validate.add_argument('--html', required=True,
	help='path to html output file')
parse_validate.add_argument('--tables', required=True,
	help='path to output directory')
parse_validate.set_defaults(func=validate_genome)

### cluster sub-command
parse_find = subparsers.add_parser('cluster',
	help='cluster related sequences')
parse_find.add_argument('--genome', required=True,
	help='genome name')
parse_find.add_argument('--location', required=True,
	help='chrom:begin-end or chrom:beg..end (commas ok)')
parse_find.add_argument('--wordsize', type=int, required=False, default=9,
	help='exact matches for seeding alignments [%(default)i]')
parse_find.add_argument('--evalue', type=float, required=False, default=1e-10,
	help='alignment E-value [%(default)g]')
parse_find.add_argument('--maxintron', type=int, required=False, default=1000,
	help='maximum HSP separation [%(default)i]')
parse_find.add_argument('--odir', required=True,
	help='path to output directory')
parse_find.add_argument('--limit', nargs='+', required=False,
	help='limit to specific genomes')
parse_find.add_argument('--cpus', type=int, required=False, default=1,
	help='number of cpus to use [%(default)i]')
parse_find.add_argument('--paralogs', action='store_true',
	help='include paralogs from host genome')
parse_find.set_defaults(func=cluster)

### sub-command checkpoint
try:
	arg = parser.parse_args()
except:
	print('seqxtant requires a sub-command, use --help for more info')
	sys.exit(1)

## Database location ##
if arg.env: env = arg.env
else:       env = os.getenv('SEQXTANT')
if not env: raise Exception('you must set SEQXTANT or use --env option')

## Run subcommand ##
arg.func(arg, env)
